// <auto-generated />
namespace Online_game_store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201907302231358_new_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
